### ISSUE TITLE
Break apart proposal

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-select2#1]
Assorted bullets I have done or need to tackle
- [x] Continuing repo history from AngularUI
- [x] Creating `component.json` with dependencies
- [x] Creating a `ui.select2` module
- [x] Change `ui.config` to `uiSelect2Config`
- [x] Create docs with subsection from demo page
- [x] Create super-dumb test runner
- [ ] Add assets as submodules(?)

**Comment by ProLoser** [comment]
In the MAIN repo I want to have the following structure:

```
/
  docs/
    index.html -> uses ng-include to pull modules/select2/docs/*
  tests/
  build/
  modules/
    select2/ -> git submodule
  component.json -> "keywords":["angular","angularui","utilities"] or "bootstrap" or "widgets" or "recommended"
  package.json
  *
```

**Comment by petebacondarwin** [comment]
Build will contain build related utils or are you thinking of build Output?

... sent from my tablet

**Comment by ProLoser** [comment]
Umm... both-ish?

I am still having mixed thoughts about just about everything. See, I wanted to have 1 repo dedicated JUST to building, but then you guys wanted us to have several modules grouped together, so I felt like having this ui repo with others as submodules might only be a redundancy.

But after playing around with folder structures and ways to efficiently add resources (git submodules, bower components, etc) I feel like I'm back to square one.

The most RELIABLE way to get 1 file I can link to for test.conf.js is with bower, but these folders aren't submodules, and they aren't even maintained by the project owners. I felt almost like sitting on everything and going back to the twitter team and telling them they're morons for forcing every single project out there to create a duplicate repo JUST for bower. 

Completely. Stupid.

I wish things were like CakePHP, git and submodules are how you manage plugins, and no one needs to build shit, or if they do, the main project takes care of it.

I feel like someone needs to develop a build system + package management system, but solutions like ender seem to go too far(?)

**Comment by petebacondarwin** [comment]
How about we create an npm module which is a grunt plugin that is
specifically created for building angular-ui modules.  Then we can easily
have separate repositories for modules.  In each repository you would have
the source files, the test specs, a simple test.config, the documentation
files a component.json, a package.json to bring in this grunt-angular-ui
module and a simple gruntFile.js that just loads up this module.  Doesn't
solve where to put the built files though :-(
