### ISSUE TITLE
View is not updated after ng-model change for fixed array of options

### ISSUE THREAD

**Issue by genuinefafa** [angular-ui/ui-select2#107]
I'm using a fixed length list of options on select2.
If I change ng-model the select2 doesn't react to model's changes.

It works with 1.0.6 and not with the latest stable version (1.2.1).

You can try it [this plnkr](http://plnkr.co/edit/fkL5iWLo47FmaCwF6nsB?p=preview).

**Comment by juanpujol** [comment]
I've the same problem two way data binding doesn't work anymore like before. Hope It'll be solved soon.

**Comment by genuinefafa** [comment]
I found out [this change](https://github.com/mchapman/ui-select2/commit/d6544d9d6b3098e8bfd31f06de79176ac90d2fe5) - thanks @fniwes - that does the trick. Maybe it should be included in the latest release of the ui-select?

**Comment by genuinefafa** [comment]
Excelent! I'll add this version to my project now ;)
