### ISSUE TITLE
select2 doesn't update the view when dynamically changing ng-model values

### ISSUE THREAD

**Issue by vlamic** [angular-ui/ui-select2#11]
Moved from: https://github.com/angular-ui/angular-ui/issues/483

After page has been loaded, the bound value is displayed correctly, but if ng-model was changed, the view gets broken.

With select2 version 3.3.1: http://plnkr.co/edit/vTFqP9pSn9QgJUkPuzRx?p=preview
You can see that after page has been loaded, the selected values are displayed. If you click "Change tags" or "Change tags2" the view gets broken.

With select version 3.2: http://plnkr.co/edit/NITfYJ1tPYatJFmK4UQJ?p=preview the view get bound to correct number of items if you click "Change tags" or "Change tags2", but the values displayed are still broken.

I guess it could work if you keep specific for select2 data format {id: "someId", text: "sometext" }, but then we loose benefits of data binding. It would be at least nice to have ability set some proxy functions to set data to and from select2 and keep bound object to ng-model the same structure as it was before.

**Comment by adiroiban** [comment]
Here is an example with latest version of select3 3.4.0 http://jsfiddle.net/hWXBv/25/

**Comment by vlamic** [comment]
Doesn't seem to be working on Mac and latest Chrome

**Comment by adiroiban** [comment]
@vlamic can you please check if these changes fix your problem:
https://github.com/angular-ui/ui-select2/pull/31

Thanks!

**Comment by vlamic** [comment]
@adiroiban, doesn't work with the code from master: http://plnkr.co/edit/wfhCHKbdSEW1ht4dqqFB?p=preview

**Comment by adiroiban** [comment]
Now I see what you are looking for:

I have fixed that here: https://github.com/angular-ui/ui-select2/pull/39

Check the example: http://plnkr.co/edit/enENOSwKbnPCzENJsftW

**Comment by adiroiban** [comment]
Beside doing dynamic update, your code is also trying to update the model using data which is not compatible with select2.

To fix that, I have implemented the 'simple_tags' options.

Not sure if this is the right way of doing it. Feedback is needed.

Thanks!

**Comment by vlamic** [comment]
Thanks! That works good!

About "simple_tags" option, maybe just name it "simple"?

**Comment by adiroiban** [comment]
Please add your comment in the pull request. There we can discuss the interface/API in that pull request. Thanks!

**Comment by BaconSoap** [comment]
Fixed in #39.
