### ISSUE TITLE
simple_tags problem with priority: 1

### ISSUE THREAD

**Issue by juanpujol** [angular-ui/ui-select2#114]
Before priority 1 on the code v0.0.2 simple_tags worked fine. Now when I try to add new values using simple_tags mode as a "tokenizer" the values are split by characters.

![screenshot 2013-12-02 16 41 54](https://f.cloud.github.com/assets/30832/1654573/89d0a624-5b4f-11e3-96e1-541a16e2da25.png)

and after adding a new value

![screenshot 2013-12-02 16 42 06](https://f.cloud.github.com/assets/30832/1654574/94f671fa-5b4f-11e3-8127-2e9254d36166.png)

Anyone had this problem? Thank you.

**Comment by Zmetser** [comment]
#115 should fix this.

**Comment by btoone** [comment]
I am experiencing the same issue. @Zmetser code in #115 seems to fix it.
