### ISSUE TITLE
select2 reset to placeholder broken (angluarjs 1.2.x)

### ISSUE THREAD

**Issue by stephenpatten** [angular-ui/ui-select2#118]
Hello,

Here is the SO http://stackoverflow.com/questions/20363466/angularui-select2-directive-unable-to-reset-to-placeholder question and the plunker with the broken behavior http://plnkr.co/edit/JrkMVt?p=preview.

I haven't found concrete documentation on what version of UI is married to AngularJS, this may be just a case of using the wrong versions together.

Thank you,
Stephen

**Comment by BaconSoap** [comment]
I forked and updated your plunkr using the latest version of ui.select2 from this repo - [see here](http://plnkr.co/edit/EtuNJ2x2XYgTihNqoC7d?p=preview). If you can update to this version of the directive then you should be set.
