### ISSUE TITLE
NgModel modes.

### ISSUE THREAD

**Issue by the-spyke** [angular-ui/ui-select2#126]
Is there an option to set ngModel not to a selected object, but to desired object property/item id?

**Comment by BaconSoap** [comment]
Hi, just to clarify: you're asking if when binding select2 to an array of objects, if you can make ng-model be the selected object's id?

**Comment by the-spyke** [comment]
Hi, yes.

**Comment by bsr203** [comment]
Hi I have same/similar question. same as http://stackoverflow.com/questions/14985346/setting-initial-values-of-angular-ui-select2-multiple-directive

What I expect is, if we feed a collection as options and and the initial selection (akin to `selected`in normal select box) should be set to the current  `ng-model`. I am not sure the `initSelection` is the right was as indicated in the SO post.

**Comment by Sharondio** [comment]
Any updates on this? I'm doing what I thought was a simple ng-model = array of selected items to initialize the select2 element, and at some point it recognizes them because the selected items are omitted from the options, but they don't show up as tags.

**Comment by Sharondio** [comment]
OK, got it working with the initSelection:

initSelection : function (element, callback) {
  callback($(element).data('$ngModelController').$modelValue);
},

But I'm with bsr203, feels a bit hacky.

**Comment by fghibellini** [comment]
there is a simple_tags option that when set to true assigns the object's id instead of the object itself to the model

**Comment by sroe** [comment]
@fghibellini 
i can't find this option in select2 docs, where did you get that info?
I've tried to set this setting but it doesn't change anything :-(.
![unbenannt](https://f.cloud.github.com/assets/6703947/2282931/bdfb4b34-9fb5-11e3-817a-87d2cab984a1.PNG)
I've bound an array with ngOptions like 'item.id as item.name for item in items' and set the ngModel to the itemId which should be selected by default...

**Comment by fghibellini** [comment]
https://github.com/angular-ui/ui-select2/blob/master/src/select2.js
lines 42 & 62

**Comment by fghibellini** [comment]
but it seems to work only when you have a multiple choice input
see https://github.com/angular-ui/ui-select2/issues/159

**Comment by sroe** [comment]
@fghibellini simple_tags is as the name says only for tags-feature, which only gets in place when isSelect = false so the convertToAngularModel and convertToSelect2Model Functions getting called.
This will not fix my problem :-(.
bsr2 was having this issue with a ajax/multiple option set, so this differes from the original question by the-spike i think. 
So the solution by Sharondi is also not solving my problem becaue initSelection is not called on singleselect.
On line 95 elm.select2('val', controller.$viewValue); is getting called which is (in my case) undefined -> which results in the output you can see in my post before. But I don't know why this is happening...
Edit:
Sorry line 95 is not getting called...
Edit2:
Okay I should read the readme carefully...:
Working with dynamic options
   ui-select2  is incompatible with  select ng-options. For the best results use  option ng-repeat instead.
Sorry for wasting your time!

**Comment by dfsq** [comment]
Any update on that?

**Comment by shawn-simon** [comment]
This is really a huge pain in the ass haha

**Comment by RedJandal** [comment]
I have done a pull request which fixes this issue. ng-model binds to the id returned by select2 and it also allows you to bind a property in your controller to the select2 data object using a ui-data attribute. 

Check it out and let me know what you think:
[https://github.com/angular-ui/ui-select2/pull/276](https://github.com/angular-ui/ui-select2/pull/276)

**Comment by snimavat** [comment]
Any updates? we load select2 with ajax array of objects, but want objects id to be bound to model

**Comment by PowerKiKi** [comment]
This project is deprecated. Fixes and new features are very unlikel yto happen. You should instead consider a migration to ui-select.
