### ISSUE TITLE
global settings

### ISSUE THREAD

**Issue by mm01** [angular-ui/ui-select2#129]
how to set  data-placeholder="-- choose --"  and {allowClear: true} for all select2 instances in one place?

**Comment by BaconSoap** [comment]
The directive provides the configuration value `uiSelect2Config` for providing a set of global defaults. For your specific case, you can do the following (assuming your module is in the `app` variable):

``` javascript
app.run(['uiSelect2Config', function(uiSelect2Config) {
    uiSelect2Config.placeholder = "-- choose --";
    uiSelect2Config.allowClear = true;
}]);
```

**Comment by mm01** [comment]
thanks!
