### ISSUE TITLE
[Question] Hide search

### ISSUE THREAD

**Issue by dspint** [angular-ui/ui-select2#130]
This parameter exists in the jQuery way of adding the select2 lib:

```
minimumResultsForSearch
```

Where you can set it to **-1** to hide the search field.

For angular, however, how do I add this as a data-attribute on the SELECT tag itself since I'm not using jQuery?

**Comment by BaconSoap** [comment]
Internally, ui-select2 uses select2, which in turn still relies on jquery.

To directly answer your question, you can pass options into ui-select2 via the attribute just like you would for regular select2:

``` html
<select ui-select2="{minimumResultsForSearch: -1}" ng-model='myModel'></select>
```

Take a look at the [options](https://github.com/angular-ui/ui-select2#options) section of the readme for more info.

**Comment by dspint** [comment]
Cheers!
