### ISSUE TITLE
ui-select2 doesn't work in editableCellTemplate of ng-grid

### ISSUE THREAD

**Issue by mrft** [angular-ui/ui-select2#131]
When I use the default select dropdown in ng-grid's editabelCellTemplate, everything behaves as expected, but when using ui-select2, picking a value always results in the list being closed and ng-grid jumping back to its 'normal' cellTemplate.

You can see this for yourself at http://jsfiddle.net/xdMDL/ or http://plnkr.co/edit/taPmlwLxZrF10jwwb1FX?p=preview

I consider this to be a bug in ui-select2, since I suppose it should be able to behave as a drop-in replacement for a normal 'select' element.

I hope someone with deep enough knowledge of ui-select2 could find out what is happening...

**Comment by BaconSoap** [comment]
This is on the ng-grid side - it's not aware of select2, which uses a different DOM structure and API than a regular input item (checkbox, dropdown, text box). It needs separate support specifically for the new type of input.

I've put together a branch that fixes the immediate problem, but note there are still more problems to using select2 - sorting a select2 column doesn't work, for instance. There's some legwork on the ng-grid side to fully integrate select2.

Take a look [at the branch](https://github.com/BaconSoap/ng-grid/tree/feature-select2). To see it in a action, replace your ng-grid include in the plunkr with: https://rawgithub.com/BaconSoap/ng-grid/feature-select2/build/ng-grid.debug.js

**Comment by mrft** [comment]
Wow, thanks for the quick reply.

One more thing: I have found another question on github that looks like it might have a similar cause (at least to me, angular is still quite new to me, so I'm not really ready yet to dig too deep into the code myself...)

http://stackoverflow.com/questions/20093892/angularjs-nggrid-issue-when-cell-editing-using-jquery-datepicker

Would it be appropriate to file a bug report for ng-grid with these 2 examples, since you seem to be treating this as a ng-grid problem rathar than a ui-select2 problem?

And one more thing I was asking myself after reading your comment: "so maybe it would work as expected if I added an invisible input to the editableCellTemplate that is linked to the same model?" This doesn't seem to work, since the ng-input directive requires the ng-model directive, to do a lot of stuff, like handle blur, and various key-presses.
In my opinion, you should be able to make the template a DIV (or anything else) with various elements in it, and this should work, even if the ng-model directive is used on some of its descendants.
Do you think it would be possible to change ng-grid in such a way that it doesn't make such strict assumptions on what an editableCellTemplate should look like? I mean, in my (somewhat naive) opinion, an editableCellTemplate might have a few rules to follow, like "it should update the model named COL_FIELD" and "it should do certain things on onblur etc.", and maybe some helper directives (like ng-input) could be created (or already exist :) ) to make adding this default behaviour for <input> elements really easy.

Because now it feels to me like you added specific code to support ui-select2, but tomorrow someone else will try to use something else inside the editableCellTemplate, and that will fail too. You can't update ng-grid for every single component that needs to be supported, so I think it makes more sense to try to create a set of rules that a template should adhere to, and then allow everyone to create any kind of template they want, as long as they follow the simple ground rules.

Does this make sense?

**Comment by BaconSoap** [comment]
I definitely agree - adding support for just the one means that it doesn't add to long-term stability. I think one important thing is that clicking on an element inside the `<div ng-input...>` shouldn't fire the blur event for that.

Another problem is that even with that fix, some plugins might create DOM nodes outside that container. I know that select2 does. And that's not even mentioning that weird sorting bug.

You're correct, that question has the same root cause and at current would also have to do a one-off hack.

I think an interesting solution to this would be some form of [adapter design pattern](http://sourcemaking.com/design_patterns/adapter), to allow consumers of ng-grid to specify how their templates behave. It's possible it already exists, but I wasn't able to see it through a quick scan of ng-grid.

I'm going to leave this ticket open for investigation.

**Comment by mrft** [comment]
The relevant stackoverflow question WITH a possible solution (without hacking ng-grid :) ).

http://stackoverflow.com/a/20813720/3087367

It might help someone else. I guess it's just a matter of adding the right information to the documentation.

**Comment by dsushmasagar** [comment]
I have similar issue with ui-select in ng-grid. @mrft Can I have working copy of this plunker?

**Comment by mrft** [comment]
Some references to external js files are wrong.
If you fix them, things should work again.
(looks like mostly files from ivaynberg on github)

2015-04-15 18:04 GMT+02:00 dsushmasagar notifications@github.com:

**Comment by dsushmasagar** [comment]
Thankyou @mrft.
