### ISSUE TITLE
trouble using for tags

### ISSUE THREAD

**Issue by joseym** [angular-ui/ui-select2#139]
So I'm attempting to use the plugin to list/add tags to an app.

It works fine used as a select box, but not for tags.

**My attempt at tag magic**

HTML

``` html
<input
  type="text"
  multiple
  ng-model="tags"
  ui-select2="options" />
```

JavaScript Config

``` javascript
var self = {
    tags: ['test1', 'test2']
  , options: {
        multiple: true
      , tags: ['one', 'two', 'three', 'four']
    }
  };
```

**Error**

> query function not defined for Select2 undefined
### Edit

So the above is as bit unclear, but is explained further in this [comment](https://github.com/angular-ui/ui-select2/issues/139#issuecomment-32769720) below.

**Comment by kbanman** [comment]
Change your javascript to 

```
$scope.options = {
    file: null
  , tags: ['test1', 'test2']
  , options: {
        multiple: true
      , tags: ['one', 'two', 'three', 'four']
    }
  };
```

**Comment by joseym** [comment]
Thanks @kbanman 

What my blurb above essentially is: 

``` javascript
$scope.file = null;
$scope.tags = ['test1', 'test2'];
$scope.options = {
    multiple: true
  , tags: ['one', 'two', 'three', 'four']
};
```

What I'm doing is extending `$scope` with `self` later

``` javascript
angular.extend($scope, self);
```

I'm assuming the relevant bits are `$scope.tags` and `$scope.options`, I should have just left `$scope.file` out.

**Comment by joseym** [comment]
So ui-select2 is nested within a directive, and I had attached that directive to tagset rather than its parent. The isolate scope wasn't interacting correctly with the plugin. I simply moved the directive attribute to the parent container and all is now well.
