### ISSUE TITLE
ng-disabled handled but throws an "Unknown method: disable" error

### ISSUE THREAD

**Issue by nathasm** [angular-ui/ui-select2#15]
Not a huge issue, but when using ng-disabled="true" causes "Unknown method: disable" to be triggered.

Select box does get disabled however.

**Comment by ProLoser** [comment]
Can you create a plunker that uses the latest source to reproduce the problem?

**Comment by leesei** [comment]
I'm also seeing this issue:

```
angular 1.0.6/1.1.4
angular-ui 0.4.0
select2 3.4.0
```

when I roll-back `select2` to 3.3.2 the error is gone

**Comment by ProLoser** [comment]
Looks like they changed the API

**Comment by ProLoser** [comment]
Fixed 6d09dc9ecb49dcc01a8ce1bd93bdc940a5d6300f

**Comment by leesei** [comment]
Thanks.
