### ISSUE TITLE
test script appears to be broken

### ISSUE THREAD

**Issue by lsiden** [angular-ui/ui-select2#167]
I followed the read-me instructions and attempted to run 'grunt'.  Here is the output: https://gist.github.com/lsiden/9388503

I fixed it as follows: https://gist.github.com/lsiden/9388528

Rant grunt again, got:  https://gist.github.com/lsiden/9388539

**Comment by lkptrzk** [comment]
@lsiden location changed again. my PR is something i did on my fork to get the tests running, so you can copy that, but a better solution would prob to lock down the version of jquery a bit better in the bower.json (or something like that)
