### ISSUE TITLE
Ability to set 'open' on Directive load (e.g. focus on load)

### ISSUE THREAD

**Issue by paullryan** [angular-ui/ui-select2#17]
According to the documents for select2 the way to set focus to the select2 element on load is to programmatically call the element.select2('open') call once the select2 root container is established. It would be great to have an option to add a focus or open attribute to this directive which would trigger this.

**Comment by ProLoser** [comment]
Does this work? `<select ui-select2 ui-jq="focus">`

or alternatively `<select ui-select2 ui-jq="select2" ui-options=" 'open' ">`

I'm merely curious of course, we _might_ end up integrating this feature.

You could also tack on `ui-watch` to have it re-fire the method again.

**Comment by ProLoser** [comment]
Here, want to try out the opener branch and tell me how it works?

**Comment by paullryan** [comment]
I will try these out this evening (MST), thanks for looking into this.

**Comment by ProLoser** [comment]
would be nice to hear back on this.

**Comment by BirdInTheCity** [comment]
How would I integrate the 'close' method?

**Comment by ProLoser** [comment]
the same thing with the word `close` where you see the word `open`

**Comment by davidwparker** [comment]
Can we get the 'opener' branch merged into master?

**Comment by igler** [comment]
+1

**Comment by lezhangxyz** [comment]
+2
