### ISSUE TITLE
'undefined' when using input.

### ISSUE THREAD

**Issue by hanifvirani** [angular-ui/ui-select2#178]
Things work fine when using select with options and ng-repeat, but there is a bug when using input along with a query. Selecting an option results in 'undefined' being displayed.

Plunker: http://plnkr.co/edit/gTy17Aym7MRseWNwrsEy?p=preview

The bug can also be seen in ui-select's demo project itself.

I did some debugging and found that on selecting an object, the watch on tAttrs.ngModel is triggered twice, once with a string and once with an object. If I return from the watch in the first case, everything works fine. 

Related issue: #134

**Comment by mark-zacharias** [comment]
As a workaround set the input type="hidden"

**Comment by jakcharlton** [comment]
Having same problem - workaround from @mark-zacharias worked

**Comment by jakcharlton** [comment]
It was also causing a double request to the Ajax end point - the first time sending the "id" as a string, the second time sending the proper object { id: '123' }

**Comment by ProLoser** [comment]
@jakcharlton does the 'workaround' fix the double request or is that still occurring?

**Comment by ProLoser** [comment]
`type=hidden` is the official solution if everything else works fine. If you guys read the Select2 documentation the instructions actually SAY use type=hidden which is why it was designed this way:

http://ivaynberg.github.io/select2/#data

**Comment by jakcharlton** [comment]
Fixes the double request too

**Comment by jakcharlton** [comment]
@ProLoser not as far as I am aware, connected to an input type=text works
just fine with Select2, only breaks with AngularUI's version

**Comment by ProLoser** [comment]
I updated the demo and readme as they were both wrong. Sorry about that guys. Please let me know if you find any other bad examples.

@jakcharlton it probably went unnoticed because single-select MIGHT work, but regardless `type=hidden` was the intended use case when I originally built ui-select and again it is specified in the select2 docs. It should not be relevant to the dev what the input type is.

**Comment by jakcharlton** [comment]
Cheers Dean, it does work that way, but it is (I'm fairly sure) now
inconsistent with Selext2 behaviour (documenter or not)

This was working fine in my app, then failed sometime recently, took a lot
of googling to find this issue
