### ISSUE TITLE
$viewValue keeps only id value with angular 1.2.15

### ISSUE THREAD

**Issue by nerezo** [angular-ui/ui-select2#189]
Hi,

I just updated version of the angularjs from 1.2.2 to 1.2.15 on my project. Seems that controller.$viewValue returns only values like this ["1"] since at 1.2.2 that was returned for example [Object { id="1", text="Sales"}]. When $viewValue return only id seems onlly "undefined" in  the area.

You can find plunkr pages for demo:
With AngularJS - 1.2.2: http://plnkr.co/edit/8VRGzh51Q5HijhpkV9JF?p=preview
With AngularJS - 1.2.15: http://plnkr.co/edit/nXW4PYJVhAFmldIIphFb?p=preview

Regards,
Okan.

**Comment by Nesse** [comment]
Hi nerezo,

I'm having the same problems. Did you find the source of the problem yet?

Regards,
Nesse

**Comment by nerezo** [comment]
Hi Nesse,

No, I deferred the upgrading angularjs for now.

Regards,
Okan.

**Comment by Nesse** [comment]
Hi Nerezo,

I've edited the file a bit and got i to work in my solution. I don't know if this is the correct way, but it works for me.

see plunkr: http://plnkr.co/edit/D1tPtzk22xiRCwvw73sF?p=preview

```
if (opts.multiple) {
    var viewValue = controller.$viewValue;

    //#region wesley

    //if (angular.isString(viewValue)) {
    //  viewValue = viewValue.split(',');
    //}

    try {
        elm.select2('data', convertToSelect2Model(viewValue));
    }catch(ex){}

    //#endregion

} else {
   ...
}
```

**Comment by nerezo** [comment]
Hi Nesse,

My workaround is like below:

```
if (opts.multiple) {
   var viewValue = controller.$viewValue;
   if (angular.isString(viewValue) && opts.simple_tags) {
      viewValue = viewValue.split(',');
   }

   if (angular.isArray(viewValue)) {
      elm.select2('data', convertToSelect2Model(viewValue));
   }
} else {
   ...
}
```

Okan.
