### ISSUE TITLE
Error: controller is undefined when using ui.select2 within a ui.bootstrap.dialog

### ISSUE THREAD

**Issue by hoangmphung** [angular-ui/ui-select2#19]
Hi,

As the title said, I'm trying to use ui.select2 (v 0.0.2) within a ui.bootstrap.dialog (v 0.3.0) and get Error: controller is undefined at line 136. I guess the problem is that the dialog controller is not yet initialized when ui.select2 tries to call it.

Would someone be able to point me to a workaround?

**Comment by ProLoser** [comment]
Hmm... I need to remove that question mark on `?ngModel`.

You forgot the `ng-model` attribute.
