### ISSUE TITLE
Travis must do `bower install` before running tests

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/ui-select2#2]
I am not sure if it's possible at this time to use bower on Travis.

**Comment by petebacondarwin** [comment]
Can't you just add
- npm install -g bower
- bower install
  to the before_script section of  .travis.yml?

**Comment by ProLoser** [comment]
Cool

**Comment by ProLoser** [comment]
I added it but now travis isn't building: https://travis-ci.org/angular-ui/ui-select2/builds/5349282

**Comment by petebacondarwin** [comment]
The problem is that you are doing "testacular run", which requires a
running testacular server.  I think you meant to do "testacular start"?
Pete

**Comment by ProLoser** [comment]
touche. thanks.

**Comment by ProLoser** [comment]
Now I just need to figure out why 13 tests are failing. Maybe the snapshot of ui-select2 I have is actually broken...

**Comment by petebacondarwin** [comment]
I notice in the build that bower is complaining that select2 requires
jquery 1.4.x whereas your angular-select2 requries >=1.8

**Comment by ProLoser** [comment]
Yeah I removed the jquery dependency completely. I realized that since select2 already specifies the jquery dependency there is no need for us to do so (since we are only injecting jquery FOR select2).

Making progress, now to just figure out why tests are failing: https://travis-ci.org/angular-ui/ui-select2/builds/5355722/#L623
