### ISSUE TITLE
createSearchChoicePosition always uses "top"

### ISSUE THREAD

**Issue by edwardysun** [angular-ui/ui-select2#205]
As per this StackOverflow post - http://stackoverflow.com/questions/22615334/ui-select2-make-adding-a-new-tag-appear-at-the-bottom-of-the-list

createSearchChoicePosition may be broken - it always uses "top" as the value even when "bottom" is specified or a function is used to change its position. Using the same settings as this JSFiddle (http://jsfiddle.net/a4Jpq/5/) with Angular still results in the new search choice field to be at the top.

**Comment by jcarenza** [comment]
+1

I'm trying to come up with a workaround in the meantime...anyone have one to share? Specifically, a solution that always keeps the 'new search choice' visible, even when a match is found. The use case is if you have a list of people and you're creating a new person who happens to have the same name as an existing person.

**Comment by jcarenza** [comment]
Actually, It's working correctly now! Make sure you're using select2 version 3.4.8 along with the latest version of ui-select2. Then, the option **createSearchChoicePosition:'bottom'** will work correctly.

**Comment by ProLoser** [comment]
on that note...
