### ISSUE TITLE
initSelection option always overrides new selections

### ISSUE THREAD

**Issue by amcdnl** [angular-ui/ui-select2#236]
When you use the `initSelection` property on the options like:

```
       initSelection : function (element, callback) {
            callback({ id: "frank", text: "Frank" });
        }
```

when I click a new value in my list such as `Sally`, it always goes back to `Frank`.

For reference from the Select2 Docs:

```
Called when Select2 is created to allow the user to initialize the selection based on the value of the element select2 is attached to.
```

**Comment by cervengoc** [comment]
Hello @amcdnl, have you found out the cause of this behaviour? I'm experiencing something similar with the latest version too.

**Comment by amcdnl** [comment]
@cervengoc I moved to ui-select :)
