### ISSUE TITLE
Minification doesn't work

### ISSUE THREAD

**Issue by PhilipAnd** [angular-ui/ui-select2#24]
I can't seem to get ui-select2 to work when minifying my JavaScript. The order of the includes is:

1) jQuery
2) AngularJS
3) Select2
3) Angular-Select2

The error I am getting is:
TypeError: Object [object Object] has no method 'select2'

**Comment by PhilipAnd** [comment]
I can see that the issue arises when I try to minify Select2, so it is probably nothing related to ui-select2

**Comment by ProLoser** [comment]
So why open an issue here? Have you tried the pre-minified version of select2 instead?

**Comment by ProLoser** [comment]
I'm going to close this issue. If it's still a problem attach a plunker that demonstrates the issue.
