### ISSUE TITLE
Add active maintainers?

### ISSUE THREAD

**Issue by pratik60** [angular-ui/ui-select2#247]
@ProLoser This repository despite being popular, is not being maintained at all. Can we at least add a few more collaborators as the owner seems to be busy?

**Comment by ProLoser** [comment]
Who do you propose I add as collaborators? I'm more than happy to add anyone with interest but I don't see any people with more than 1 patch here or there.

**Comment by pratik60** [comment]
@ProLoser - That's your call, I'm very new on the scene when it comes to this repository. Just been actively using it for the past 10 days. :-(

Volunteers, step up. Now, is your time to shine :-)

On a serious note, those who ask for collaborator access, you will just have to go by their github profiles, and how actively they have been a part here. I'm hopeful, there will be a few that fit what you are looking for.

P.S. - Just added a minor pull request for updating jquery link in the demo.

**Comment by ProLoser** [comment]
No one has asked for commit access specifically that I'm aware of. Most people just want someone else to fix it. Even those nice enough to open a Pull Request aren't really looking to take on the responsibility of handling all the open requests on the project. 

The project has become a bit... overly complicated. A new effort for a more simplified version was started here: https://github.com/angular-ui/ui-select which is a bit more active and 100% angular. It's skinnable to resemble select2, bootstrap, whatever.

**Comment by vendethiel** [comment]
Glad to see there's efforts in something angular-native that won't have the burden of select2.

EDIT: removed the rest of the message, as those were gripe I had with older versions of the plugin.

**Comment by PowerKiKi** [comment]
@ProLoser would you accept a PR to modify the Readme and clarify the situation ? I would officially declare this project as obsolete and replaced with the "better" 100% angular ui-select ?

So people would not get false hope of getting things solved here. Also editing the project setting to remove issue tracker could avoid unnecessary noise for you...

**Comment by ProLoser** [comment]
Does such a PR exist? I didn't know if anyone else took over the project or not but I guess you are right.

**Comment by PowerKiKi** [comment]
I created a PR for you. 

For the issue tracker, I think if you deactivate it, the history will not be available anymore. I don't know if there is a read-only mode. So that's up to you to decide... you could also close all pending issue and briefly explain it is deprecated
