### ISSUE TITLE
xss attack

### ISSUE THREAD

**Issue by Hsinglin** [angular-ui/ui-select2#262]
select2.js
 `line 937`

```
label.html(formatted);
```

it will trigger a xss attack.

**Comment by doliveirakn** [comment]
+1

**Comment by asm0dey** [comment]
:+1:

**Comment by PowerKiKi** [comment]
ui-select2 is deprecated, you should consider using https://github.com/angular-ui/ui-select instead. It is very unlikely that this project will be updated from now on.

**Comment by asm0dey** [comment]
It's impossible for us to migrate to ui-select until they'll support infinite scrolling...
