### ISSUE TITLE
Geting an error when used inside a custom directive

### ISSUE THREAD

**Issue by kbanglore** [angular-ui/ui-select2#27]
Hi

I'm getting the following error when I tried using select2 inside my custom directive.

[08:18:07.412] Error: tElm.is is not a function
.compile@http://localhost:1981/Scripts/select2.js:19
A@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:46
$/<@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:49
u/j.success/<@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:100
Uc/e/j.promise.then/i@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:79
Uc/e/j.promise.then/i@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:79
Uc/g/<.then/<@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:80
e.prototype.$eval@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:92
e.prototype.$digest@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:90
e.prototype.$apply@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:92
j@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:101
r@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:104
dd/</v.onreadystatechange@http://localhost:1981/Scripts/angularjs/1.1.5/angular.min.js:106
 <select include-accounts="1" show-indirect-access-monikers="1" on-moniker-change="ProcessMonikerChange" id="jprimeManager" ui-select2="{ allowClear: true}" ng-model="select2" data-placeholder="Choose a Manager...">

**Comment by ProLoser** [comment]
What is the contents of the line in question? Or more accurately, the contents of the file?

**Comment by ProLoser** [comment]
Ah, you're missing jQuery. This module requires select2 which in turn requires jQuery.

**Comment by zinking** [comment]
`Error: tElm.is is not a function
.compile@http://minelocal/lib/angular-ui-select2/src/select2.js:20:20
applyDirectivesToNode@http://minelocal/lib/ionic/js/ionic.bundle.js:16757:22
compileNodes@http://minelocal/lib/ionic/js/ionic.bundle.js:16286:15
compileNodes@http://minelocal/lib/ionic/js/ionic.bundle.js:16298:15
compileNodes@http://minelocal/lib/ionic/js/ionic.bundle.js:16298:15
compileNodes@http://minelocal/lib/ionic/js/ionic.bundle.js:16298:15
compileNodes@http://minelocal/lib/ionic/js/ionic.bundle.js:16298:15
compileNodes@http://minelocal/lib/ionic/js/ionic.bundle.js:16298:15
compile@http://minelocal/lib/ionic/js/ionic.bundle.js:16193:15
self.appendViewElement@http://minelocal/lib/ionic/js/ionic.bundle.js:52247:18
ionicViewSwitcher.create/switcher.render@http://minelocal/lib/ionic/js/ionic.bundle.js:50449:29
ionicViewSwitcher.create/switcher.init@http://minelocal/lib/ionic/js/ionic.bundle.js:50369:11
self.render@http://minelocal/lib/ionic/js/ionic.bundle.js:52115:5
self.register@http://minelocal/lib/ionic/js/ionic.bundle.js:52073:5
updateView@http://minelocal/lib/ionic/js/ionic.bundle.js:57485:11
.compile/</<@http://minelocal/lib/ionic/js/ionic.bundle.js:57462:11
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://minelocal/lib/ionic/js/ionic.bundle.js:24992:15
transitionTo/$state.transition<@http://minelocal/lib/ionic/js/ionic.bundle.js:44836:11
processQueue@http://minelocal/lib/ionic/js/ionic.bundle.js:23394:28
scheduleProcessQueue/<@http://minelocal/lib/ionic/js/ionic.bundle.js:23410:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://minelocal/lib/ionic/js/ionic.bundle.js:24673:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://minelocal/lib/ionic/js/ionic.bundle.js:24484:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://minelocal/lib/ionic/js/ionic.bundle.js:24778:13
@http://minelocal/lib/ionic/js/ionic.bundle.js:57513:7
createEventHandler/eventHandler@http://minelocal/lib/ionic/js/ionic.bundle.js:12098:9
triggerMouseEvent@http://minelocal/lib/ionic/js/ionic.bundle.js:2865:3
tapClick@http://minelocal/lib/ionic/js/ionic.bundle.js:2854:3
tapMouseUp@http://minelocal/lib/ionic/js/ionic.bundle.js:2927:5`

I think I included query

**Comment by zinking** [comment]
tried a few attempts, seems the importing sequence matters as well. not sure why, but solves my question
