### ISSUE TITLE
Using search string as parameter to get the list

### ISSUE THREAD

**Issue by fboucquez** [angular-ui/ui-select2#285]
Hi, the list the user can select from is dynamically loaded from backend depending on what's the user is typing. Is it possible to have a reference to that text? 

``` html
<select  ng-model="formData.itemKey" ui-select2>
    <option value="{{item.key}}" ng-repeat="item in getList($select2.query???)">{{item.name}}</option>
</select>
```

Thanks!
Fernando

**Comment by PowerKiKi** [comment]
ui-select2 is deprecated, you should use https://github.com/angular-ui/ui-select instead. Also this does not sounds like a bug report, but a request for support. StackOverflow would be more appropriate: http://stackoverflow.com/questions/tagged/ui-select2
