### ISSUE TITLE
$watchCollection is not triggered on multiple select

### ISSUE THREAD

**Issue by tb** [angular-ui/ui-select2#287]
I had an issue with 

```
$scope.$watchCollection 'selectedCollection', -> 
```

not being triggered on

```
ng-model='selectedCollection'
```

It turns out this is not bug in select2, but rather issue with how ng-model and isolated scope work.

What fixed it for me was:

```
$scope.params.selectedCollection = {}
$scope.$watchCollection 'params.selectedCollection', -> 
```

and

```
ng-model='params.selectedCollection'
```

**Comment by PowerKiKi** [comment]
ui-select2 is deprecated, you should consider using https://github.com/angular-ui/ui-select instead. It is very unlikely that this project will be updated from now on.
