### ISSUE TITLE
Unable to add tooltip in input box

### ISSUE THREAD

**Issue by ramprakash-ravi** [angular-ui/ui-select2#294]
I tried adding tooltip to input box in ui-select but its not working.

input(type='hidden', ui-select2='userSelect2options', data-placeholder='All User',
ng-model='selectedUsersForFilter', style='width:100%; margin-left:5px;',ng-readonly='isUserSelectDisabled', tooltip='Please select atleast one User')

How to add tool tip for input box in ui-select2 ?

**Comment by PowerKiKi** [comment]
Please ask question on stackoverflow: http://stackoverflow.com/questions/tagged/ui-select2

Also note that this project is dead. Instead use ui-select.
