### ISSUE TITLE
Select2 closeOnSelect issue

### ISSUE THREAD

**Issue by johntom** [angular-ui/ui-select2#3]
Hi,
I originally wrote this issue on the angular-ui site and will give it a try here. This feature would allow the end-user to make multiple selections without pressing in the box each time.
I'm using version 3.3.1 of select2, 0.4.0 of angular-ui and setting multiple="multiple" and closeOnSelect='false' but the close event happens regardless of setting. The following illustrates issue.
http://plnkr.co/edit/y4tTumkYPjlwqomWfKNQ?p=preview
TIA
John

**Comment by johntom** [comment]
This feature now works! Thanks

**Comment by M-Wittner** [comment]
Still doesn't work for me
