### ISSUE TITLE
The select2('val') method was called on an element that is not using Select2

### ISSUE THREAD

**Issue by patilharshal16** [angular-ui/ui-select2#316]
I am using Select2 4.0.5 version while updating the selected values of element I am facing this issue although I tried initializing select2 on element initially and then adding selected values again without initializing select2 on the element I tried adding selected values also did vise-versa.

**Comment by beta1007** [comment]
Update the following to look for class name.

elm.bind("$destroy", function () {
          if (elm.hasClass('.select2-offscreen')) {
            elm.select2("destroy");
          }
        });

**Comment by patilharshal16** [comment]
@beta1007 thanks for the update. I already fixed this issue.
