### ISSUE TITLE
Update bower package

### ISSUE THREAD

**Issue by pheuter** [angular-ui/ui-select2#33]
Changelog shows ui-select2 is current at version 0.0.4, but bower.json shows 0.0.2. It would be great if it could reflect the latest version. Also, a 0.0.4 tag needs to be created for the repo.

**Comment by ProLoser** [comment]
Actually the changelog is old/wrong and I should probably just delete it. It's a vestigial file from when ui-select2 was part of a larger AngularUI repo.
