### ISSUE TITLE
Missing 0.0.1 git tag for Bower

### ISSUE THREAD

**Issue by Iristyle** [angular-ui/ui-select2#4]
For Bower to pull this in with a version, you also need to use a git tag.

If I include  `"angular-ui-select2": "0.0.1"` in my `components.json`, then Bower fails with.

```
Fatal error: Could not find tag satisfying: angular-ui-select2#0.0.1
```

`latest` will work for now, but I prefer to never use a version specifier like that.

**Comment by Iristyle** [comment]
FYI -- Versioning this component for Bower with git tags is a big issue.  When `ui-select2.js` was renamed to `select2.js` our build was broken as a result.

All you need to do is pick a commit and tag it, matching the git tag to what's in `component.json`.  Push it up and you're done.

```
git tag 0.0.1 COMMITSHA
git push --tags
```

**Comment by ProLoser** [comment]
Was in pre-alpha as we are still figuring things out but I put in a 0.0.1 tag
