### ISSUE TITLE
Typeahead not working in single select

### ISSUE THREAD

**Issue by kpgarrod** [angular-ui/ui-select2#67]
I am using ui-select2 quite extensively in my project with the 'multiple' option. It all works fine.

I have a couple of places where I need a select box with a single option. I would like to use ui-select2, but I find that I am not able to focus in the search box. Here is the tag. I am not using any options in the controller.

``` html
          <select 
            ui-select2
            data-placeholder="Choose a country"
            ng-model="bla.country"
            class= 'input-large'>
            <option ng-repeat = 'c in countries' 
              value='{{c.code}}'>
              {{c.name}}
            </option>
          </select>
```

**Comment by ProLoser** [comment]
Can you create a plunker or fiddle?

**Comment by kpgarrod** [comment]
Sorry, I haven't managed to extract a plunkr, but I think I have narrowed
the problem down to modals. I am using a single select with 'identical'
code outside of a modal and it works perfectly. Hope that helps.

On 2 September 2013 02:41, Dean Sofer notifications@github.com wrote:

> Can you create a plunker or fiddle?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/ui-select2/issues/67#issuecomment-23636560
> .

## 

Keith Garrod

Tel: +27-83-3000-988
Fax: +27-86-5757781

**Comment by Phlow2001** [comment]
@kpgarrod Focus issues in IE bootstrap modal is a known issue, if that's what you're referring to.  There is a work-around  Not a problem with ui-select2, or select2.  Have a look at https://github.com/ivaynberg/select2/issues/942

**Comment by ProLoser** [comment]
@Phlow2001 thanks
