### ISSUE TITLE
how do i set a preset value of when using data: and json

### ISSUE THREAD

**Issue by btm1** [angular-ui/ui-select2#70]
I've got got a big list of json with properties and children.  When i save them off to the database i save the selected value which looks like this:

{
      "label": "Annual Revenue",
      "rules": [
        "is",
        "is not",
        "less then",
        "greater then"
      ],
      "value": {
        "type": "number"
      },
      "text": "Annual Revenue",
      "field": "AnnualRevenue",
      "id": "AnnualRevenue",
      "category": "salesForceLead"
    }

how do i preset the value so that when the select 2 direct inits it reads the value off of my ng-model and then sets it in the dropdown... i've tried everything. Basically if i put any value in the ng-model and then select2 inits it overrides my ng-model value with a blank one.

**Comment by jeffpogo** [comment]
Add a initSelection to your select2Options

```
               initSelection : function (element, callback) {
                    var val = $(element).val();
                    callback({id: val, text: val});
                },
```
