### ISSUE TITLE
How to use angular bootstrap tooltips inside ui-select2

### ISSUE THREAD

**Issue by jmwolfe** [angular-ui/ui-select2#79]
Can anyone suggest how I can use ui-boostrap tooltips inside the select2?

I can inject the right tooltip attributes via formatResult/formatSelection select2 callbacks like this:

``` javascript
       $scope.formatClient = function (c) {
            var desc = "";
            if (c.description !== undefined) {
                desc = c.description.replace('"', "&dquot;");
            }

            return ('<span tooltip-placement="top" tooltip="' + desc + '" title="' + desc + '">' + c.text + '</span>');

        };
```

 but it looks like be the time its all output its too late for angular to catch the directives and run them.

Looks like my ui-jq might be able to do it, but it's over my head. Just using it plainly out of the box doesn't work either.

Right now I'm stuck with default title tags.

help!

**Comment by jmwolfe** [comment]
I posted on the Google group and got some responses. The only way to do this is to use the jquery native tooltips. One "bad" thing about it tho is that you must use top/bottom tool tips because right/left get hidden due to the nature of the select2 dropdown.

So I used this format option for select2:

``` javascript
        $scope.formatClient = function (c) {
            var desc = "", placement = 'top';
            if (c.description !== undefined) {
                desc = c.description.replace('"', "&dquot;");
            }
            if (c.index == 0) {
                placement = 'bottom';
            }
            return ('<div class="cm-tooltip" data-placement="' + placement + '" title="' + desc + '">' + c.text + '</div>');
        };
```

Notice I had to put in some logic to flip the topmost tooltip (since it would not be visible!).

After loading your data (like in a success callback to $resource), you have to do this to apply the tooltips dynamically:

``` javascript
            // since angular can't process jquery emitted tooltips from the select2, we have to manage
            // assigning the tooltips ourselves after we have our data in. This will go in a directive
            // once we get there.
            $('body').tooltip(
                {
                    selector: '.cm-tooltip',
                    container: 'body',
                    delay: { show: 500, hide: 100 },
                });

```

**Comment by chessydk** [comment]
Hello jmwolfe - did you get it to work 100% ? The tooltip over the selected option works fine, but for the options in the dropdown the tooltip shows under the dropdown and also stays displayed when I select an option...
