### ISSUE TITLE
select2 doesn't get initialized correctly when using nested ng-repeat with optgroup

### ISSUE THREAD

**Issue by tadchristiansen** [angular-ui/ui-select2#8]
I posted the following issue stackoverflow (contains a jsfiddle that shows the issue):

http://stackoverflow.com/questions/16123704/how-to-get-select2-tags-initializing-correctly-with-angular-ui-when-option-group

I have tried digging in to angular-ui to see if I can find what keeps it from getting initialized but the code looks correct:

if (isSelect) {
elm.select2('val', controller.$modelValue);
}

controller.$modelValue is set correctly so it seems like its some kind of refresh issue.

http://jsfiddle.net/tadchristiansen/QRRYf/

**Comment by DiegoPires** [comment]
Have you tried to update your angularui? After they have separated in more files and modules they have also changed some things...

This part you pointed changed to use the $viewValue now, and in the inicialization of the select2 there`s a couple more of validations too

https://github.com/angular-ui/ui-select2/blob/master/src/select2.js

**Comment by tadchristiansen** [comment]
I tried this tonight. Looks like it is now working. Thanks!

**Comment by ProLoser** [comment]
I love it when a plan comes together
