### ISSUE TITLE
select2 never initialized when using <input type="hidden"> for tagging

### ISSUE THREAD

**Issue by aozora** [angular-ui/ui-select2#9]
I have the following html:

``` html
<input data-ui-select2="defaultTags" 
       data-ng-model="item.Tags" 
       class="tag-list" 
       type="hidden" 
       value="importante, c123, gianluca"/>
```

in console I get this error: "query function not defined for Select2 undefined"

Using pure jquery plugin like the following it was working as expected:

``` javascript
$('.tag-list', $target).select2({
   tags: ["importante", "da leggere"]
   , placeholder: 'aggiungi tag...'
});
```

but with ui-select2 don't work, giving the above error.

**Comment by ProLoser** [comment]
What is defaultTags?

**Comment by aozora** [comment]
Is defined in the controller as:
$scope.defaultTags=['tag1','tag2'];

**Comment by ProLoser** [comment]
You are doing it wrong.

Select2= should be your configuration options. Value= is completely
ignored. You should set the initial values in the controller to the model
value.

**Comment by aozora** [comment]
Please, what is the correct way to pass configuration option ui-select2 ?

**Comment by aozora** [comment]
If I try like this: 

```
<input data-ui-select2="tags: ["importante", "da leggere"], placeholder: 'aggiungi tag...'" 
       data-ng-model="item.Tags" 
       class="tag-list" 
       type="hidden" />
```

but I get this error:
`Error: Syntax Error: Token ':' is an unexpected token at column 5 of the expression [tags: [] starting at [: [].`

also without specifying any option in data-uio-select2, I get this:
`query function not defined for Select2 undefined`
