### ISSUE TITLE
Support Angular 1.2

### ISSUE THREAD

**Issue by OndraM** [angular-ui/ui-select2#91]
I only noted Bower dependency was recently locked to angular <1.2, but I did not find any issue addressing the 1.2 support. So here is a one :).

Any plans getting uiSelect2 working under Angular 1.2?

Thanks
Ondrej

**Comment by aantipov** [comment]
Also interested in this issue

**Comment by mchapman** [comment]
Not an attempt to support 1.2, but if your requirements do not include multi then you will still need a tiny change which I have done at https://github.com/mchapman/ui-select2/commit/d6544d9d6b3098e8bfd31f06de79176ac90d2fe5

**Comment by juanpujol** [comment]
@mchapman Man! thank you very much, This solved the sync with ngModel issue for me.

**Comment by maxisam** [comment]
Here is the case regarding the change https://github.com/angular/angular.js/commit/31f190d4

http://plnkr.co/edit/1YmQTfdfUr6AvUBUnmWL?p=preview

in 1.2 RC2 or previous version

It works fine. I can use select2OptionsL / select2OptionsC for ui-select2

But in 1.2 RC3 it doesn't work if I use select2OptionsL for ui-select2.

**Comment by mrzmyr** [comment]
+1 for [angular 1.2](http://blog.angularjs.org/2013/11/angularjs-120-timely-delivery.html) support

**Comment by juanpujol** [comment]
maxisam, same problem here. If I try to config the options on the link function of a directive, I got hits: 

`query function not defined for Select2 country-field`

Before this was working.

Thank you.

**Comment by jrust** [comment]
+1 subscribing.

**Comment by thnk2wn** [comment]
Also interested; here's a plunker showing dropdown values not working correctly with 1.2  

http://plnkr.co/edit/unQGrqUr7IJinDEioERf?p=preview

**Comment by thnk2wn** [comment]
@mchapman thanks for the workaround until this is supported.

**Comment by smajl** [comment]
+1 for official support.

**Comment by ProLoser** [comment]
If you guys fix the broken tests with https://github.com/angular-ui/ui-select2/pull/104 we can merge it and you'll have 1.2 support

**Comment by matrasmusson** [comment]
This fixed problem with multiple as well, not just dropdown. +1 for official support.

**Comment by ProLoser** [comment]
@mchapman: next time add a pull request. 

This is in version 0.0.4

**Comment by michaelnatkin** [comment]
I'm having what might be a related problem here: http://stackoverflow.com/questions/21347714/trying-to-use-angular-ui-select2-in-tag-mode-not-simple-tag-losing-objects - is it possible I've just stumbled across another case that doesn't work in 1.2X?
